artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/0f3fa0640e054410aebb61dbfd04b353/artifacts
end_time: 1667224182669
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 0f3fa0640e054410aebb61dbfd04b353
run_uuid: 0f3fa0640e054410aebb61dbfd04b353
source_name: ''
source_type: 4
source_version: ''
start_time: 1667223930232
status: 3
tags: []
user_id: fis00claupere
