artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/62cbbad3b9c147ec97b1a2da1e655164/artifacts
end_time: 1667218843660
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 62cbbad3b9c147ec97b1a2da1e655164
run_uuid: 62cbbad3b9c147ec97b1a2da1e655164
source_name: ''
source_type: 4
source_version: ''
start_time: 1667218591607
status: 3
tags: []
user_id: fis00claupere
