artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/4fc72b417a7d4a95947b7cfe1a9eee48/artifacts
end_time: 1667212994924
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 4fc72b417a7d4a95947b7cfe1a9eee48
run_uuid: 4fc72b417a7d4a95947b7cfe1a9eee48
source_name: ''
source_type: 4
source_version: ''
start_time: 1667212742424
status: 3
tags: []
user_id: fis00claupere
