artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/c6fc150147bb4ae3ae2fd3740d00cdbe/artifacts
end_time: 1667221131834
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c6fc150147bb4ae3ae2fd3740d00cdbe
run_uuid: c6fc150147bb4ae3ae2fd3740d00cdbe
source_name: ''
source_type: 4
source_version: ''
start_time: 1667220881355
status: 3
tags: []
user_id: fis00claupere
