artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/ba9bf722aca74ae3a45800147d564d14/artifacts
end_time: 1667218587948
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: ba9bf722aca74ae3a45800147d564d14
run_uuid: ba9bf722aca74ae3a45800147d564d14
source_name: ''
source_type: 4
source_version: ''
start_time: 1667218338187
status: 3
tags: []
user_id: fis00claupere
