artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/a4f4642eee8e43798309b474b6c6b742/artifacts
end_time: 1667211468508
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: a4f4642eee8e43798309b474b6c6b742
run_uuid: a4f4642eee8e43798309b474b6c6b742
source_name: ''
source_type: 4
source_version: ''
start_time: 1667211217092
status: 3
tags: []
user_id: fis00claupere
