artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/ecfa332b17784d0d970c21dc238ba7f6/artifacts
end_time: 1667224436432
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: ecfa332b17784d0d970c21dc238ba7f6
run_uuid: ecfa332b17784d0d970c21dc238ba7f6
source_name: ''
source_type: 4
source_version: ''
start_time: 1667224186044
status: 3
tags: []
user_id: fis00claupere
