artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/9482a80a9b9d46c19d295b53b79e4c0c/artifacts
end_time: 1667223673027
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 9482a80a9b9d46c19d295b53b79e4c0c
run_uuid: 9482a80a9b9d46c19d295b53b79e4c0c
source_name: ''
source_type: 4
source_version: ''
start_time: 1667223423597
status: 3
tags: []
user_id: fis00claupere
