artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/b216f366f4f14415ae9c05370cfd0eb1/artifacts
end_time: 1667217827146
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: b216f366f4f14415ae9c05370cfd0eb1
run_uuid: b216f366f4f14415ae9c05370cfd0eb1
source_name: ''
source_type: 4
source_version: ''
start_time: 1667217576313
status: 3
tags: []
user_id: fis00claupere
