artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/21dad26a78fd45ecb7528d45f328aa68/artifacts
end_time: 1667221894918
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 21dad26a78fd45ecb7528d45f328aa68
run_uuid: 21dad26a78fd45ecb7528d45f328aa68
source_name: ''
source_type: 4
source_version: ''
start_time: 1667221644607
status: 3
tags: []
user_id: fis00claupere
