artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/391ff4bac94e4b0b85cacfb92ba3a520/artifacts
end_time: 1667211973035
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 391ff4bac94e4b0b85cacfb92ba3a520
run_uuid: 391ff4bac94e4b0b85cacfb92ba3a520
source_name: ''
source_type: 4
source_version: ''
start_time: 1667211724017
status: 3
tags: []
user_id: fis00claupere
