artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/c989036305b94918ba5d4435ab3c5af3/artifacts
end_time: 1667216304642
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c989036305b94918ba5d4435ab3c5af3
run_uuid: c989036305b94918ba5d4435ab3c5af3
source_name: ''
source_type: 4
source_version: ''
start_time: 1667216054648
status: 3
tags: []
user_id: fis00claupere
