artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/fce40d7eeda041d9bea0db8422a95d4a/artifacts
end_time: 1667213755897
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: fce40d7eeda041d9bea0db8422a95d4a
run_uuid: fce40d7eeda041d9bea0db8422a95d4a
source_name: ''
source_type: 4
source_version: ''
start_time: 1667213508141
status: 3
tags: []
user_id: fis00claupere
