artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/424d0d2b1a5946299d028e8d4ed1c30f/artifacts
end_time: 1667217321490
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 424d0d2b1a5946299d028e8d4ed1c30f
run_uuid: 424d0d2b1a5946299d028e8d4ed1c30f
source_name: ''
source_type: 4
source_version: ''
start_time: 1667217072504
status: 3
tags: []
user_id: fis00claupere
