artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/07a328b3935d4264bf2ba8baea9a7b32/artifacts
end_time: 1667223926675
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 07a328b3935d4264bf2ba8baea9a7b32
run_uuid: 07a328b3935d4264bf2ba8baea9a7b32
source_name: ''
source_type: 4
source_version: ''
start_time: 1667223676490
status: 3
tags: []
user_id: fis00claupere
