artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/5057ac15f51447e49a349036bbdde3e1/artifacts
end_time: 1667212483544
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 5057ac15f51447e49a349036bbdde3e1
run_uuid: 5057ac15f51447e49a349036bbdde3e1
source_name: ''
source_type: 4
source_version: ''
start_time: 1667212232383
status: 3
tags: []
user_id: fis00claupere
