artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/4c5db0013d184dc8b3ddfaa4ab3e0f4f/artifacts
end_time: 1667219605938
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 4c5db0013d184dc8b3ddfaa4ab3e0f4f
run_uuid: 4c5db0013d184dc8b3ddfaa4ab3e0f4f
source_name: ''
source_type: 4
source_version: ''
start_time: 1667219354884
status: 3
tags: []
user_id: fis00claupere
