artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/c44d3be72e2c4015853750a789b791bd/artifacts
end_time: 1667210958498
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c44d3be72e2c4015853750a789b791bd
run_uuid: c44d3be72e2c4015853750a789b791bd
source_name: ''
source_type: 4
source_version: ''
start_time: 1667210707344
status: 3
tags: []
user_id: fis00claupere
