artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/76a0ec1845ad43e7a10d02209abfa4d1/artifacts
end_time: 1667221386495
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 76a0ec1845ad43e7a10d02209abfa4d1
run_uuid: 76a0ec1845ad43e7a10d02209abfa4d1
source_name: ''
source_type: 4
source_version: ''
start_time: 1667221135540
status: 3
tags: []
user_id: fis00claupere
