artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/6e5f9956321b40afa1e21a685540ae51/artifacts
end_time: 1667211213738
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 6e5f9956321b40afa1e21a685540ae51
run_uuid: 6e5f9956321b40afa1e21a685540ae51
source_name: ''
source_type: 4
source_version: ''
start_time: 1667210961888
status: 3
tags: []
user_id: fis00claupere
