artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/1f7d1b29dbe345a98b205662d9d9bc6d/artifacts
end_time: 1667214012181
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 1f7d1b29dbe345a98b205662d9d9bc6d
run_uuid: 1f7d1b29dbe345a98b205662d9d9bc6d
source_name: ''
source_type: 4
source_version: ''
start_time: 1667213759479
status: 3
tags: []
user_id: fis00claupere
