artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/4304f5cfee6c48e498b053ac9bd97381/artifacts
end_time: 1667210195389
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 4304f5cfee6c48e498b053ac9bd97381
run_uuid: 4304f5cfee6c48e498b053ac9bd97381
source_name: ''
source_type: 4
source_version: ''
start_time: 1667209944949
status: 3
tags: []
user_id: fis00claupere
