artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/3c63a1e8da884c449441a4abcebf25cd/artifacts
end_time: 1667220877574
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 3c63a1e8da884c449441a4abcebf25cd
run_uuid: 3c63a1e8da884c449441a4abcebf25cd
source_name: ''
source_type: 4
source_version: ''
start_time: 1667220627632
status: 3
tags: []
user_id: fis00claupere
