artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/0aabd8b3b938437ca92fbf58250d4105/artifacts
end_time: 1667219351469
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 0aabd8b3b938437ca92fbf58250d4105
run_uuid: 0aabd8b3b938437ca92fbf58250d4105
source_name: ''
source_type: 4
source_version: ''
start_time: 1667219099761
status: 3
tags: []
user_id: fis00claupere
