artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/749d977c8cdf4b58a86aee6abf6af093/artifacts
end_time: 1667220368939
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 749d977c8cdf4b58a86aee6abf6af093
run_uuid: 749d977c8cdf4b58a86aee6abf6af093
source_name: ''
source_type: 4
source_version: ''
start_time: 1667220120139
status: 3
tags: []
user_id: fis00claupere
