artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/203208be568c4aaf8a4418c0e9193178/artifacts
end_time: 1667224691959
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 203208be568c4aaf8a4418c0e9193178
run_uuid: 203208be568c4aaf8a4418c0e9193178
source_name: ''
source_type: 4
source_version: ''
start_time: 1667224439924
status: 3
tags: []
user_id: fis00claupere
