artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/9767427cebae4ea4ae35e51b9d7a8f26/artifacts
end_time: 1667214266125
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 9767427cebae4ea4ae35e51b9d7a8f26
run_uuid: 9767427cebae4ea4ae35e51b9d7a8f26
source_name: ''
source_type: 4
source_version: ''
start_time: 1667214015669
status: 3
tags: []
user_id: fis00claupere
