artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/10f395875ace49b5b7195ee6d7cfbe2f/artifacts
end_time: 1667222909274
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 10f395875ace49b5b7195ee6d7cfbe2f
run_uuid: 10f395875ace49b5b7195ee6d7cfbe2f
source_name: ''
source_type: 4
source_version: ''
start_time: 1667222660649
status: 3
tags: []
user_id: fis00claupere
