artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/ea7a302f9135480293cfd8d2d162c00d/artifacts
end_time: 1667216050963
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: ea7a302f9135480293cfd8d2d162c00d
run_uuid: ea7a302f9135480293cfd8d2d162c00d
source_name: ''
source_type: 4
source_version: ''
start_time: 1667215799092
status: 3
tags: []
user_id: fis00claupere
