artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/8bcf2150f10c4a56ac69cfc699f19d06/artifacts
end_time: 1667220624071
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 8bcf2150f10c4a56ac69cfc699f19d06
run_uuid: 8bcf2150f10c4a56ac69cfc699f19d06
source_name: ''
source_type: 4
source_version: ''
start_time: 1667220372336
status: 3
tags: []
user_id: fis00claupere
