artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/bc0f4bd038044b04af20836be0771885/artifacts
end_time: 1667224972298
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: bc0f4bd038044b04af20836be0771885
run_uuid: bc0f4bd038044b04af20836be0771885
source_name: ''
source_type: 4
source_version: ''
start_time: 1667224695076
status: 3
tags: []
user_id: fis00claupere
