artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/88fdc3ce1af146479aab663734427117/artifacts
end_time: 1667216558698
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 88fdc3ce1af146479aab663734427117
run_uuid: 88fdc3ce1af146479aab663734427117
source_name: ''
source_type: 4
source_version: ''
start_time: 1667216308041
status: 3
tags: []
user_id: fis00claupere
