artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/610ed504cfae4bfeac5d42ae495de94c/artifacts
end_time: 1667215031056
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 610ed504cfae4bfeac5d42ae495de94c
run_uuid: 610ed504cfae4bfeac5d42ae495de94c
source_name: ''
source_type: 4
source_version: ''
start_time: 1667214778652
status: 3
tags: []
user_id: fis00claupere
