artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/4ef40eaf86ae4f8f9a25a0a2c5bf04c8/artifacts
end_time: 1667212228736
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 4ef40eaf86ae4f8f9a25a0a2c5bf04c8
run_uuid: 4ef40eaf86ae4f8f9a25a0a2c5bf04c8
source_name: ''
source_type: 4
source_version: ''
start_time: 1667211976659
status: 3
tags: []
user_id: fis00claupere
