artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/e2040e0e1f8143fa89382eb408f0b836/artifacts
end_time: 1667216813712
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: e2040e0e1f8143fa89382eb408f0b836
run_uuid: e2040e0e1f8143fa89382eb408f0b836
source_name: ''
source_type: 4
source_version: ''
start_time: 1667216562103
status: 3
tags: []
user_id: fis00claupere
