artifact_uri: /home/fis00claupere/AISC/project_aisc/data/experiments/mlruns/2/835c3c08da5843f7ac1b00ced001e394/artifacts
end_time: 1667218334526
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 835c3c08da5843f7ac1b00ced001e394
run_uuid: 835c3c08da5843f7ac1b00ced001e394
source_name: ''
source_type: 4
source_version: ''
start_time: 1667218085163
status: 3
tags: []
user_id: fis00claupere
